export default [
  {
    type: "shoes",
    brandName: "Grinta",
    description: "Grinta_Men_Fashion Sneakers-Black_44EU",
    price: 209.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "activ",
    description: "ACTIV CASUAL FASHION SHOES,WHITE,39",
    price: 599.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Reebok",
    description: "Reebok FLOATRIDE ENERGY 3.0 Shoes for Men white EU",
    price: 1.369,
    images: [],
  },
  {
    type: "shoes",
    brandName: "adidas",
    description: "adidas Unisex Kids Predator Edge.4 Tf J, Color",
    price: 789.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Adidas",
    description: "Adidas VULCRAID3R",
    price: 1.289,
    images: [],
  },
  {
    type: "shoes",
    brandName: "adidas",
    description: "Adidas VULCRAID3R K GZ3334 SKATEBOARDING",
    price: 949.99,
    images: [],
  },
  {
    type: "shoes",
    brandName: " adidas",
    description: "Adidas LITE RACER 3.0 GW3023 RUNNING",
    price: 1.089,
    images: [],
  },
  {
    type: "shoes",
    brandName: "adidas",
    description: "Adidas X Ghosted.1 Textile Two-Tone Printed Front",
    price: 500.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Generic",
    description: "Romba Sport Shoes For Men",
    price: 199.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "salerno",
    description: "Salerno Mesh Leather-Accent Contrast Side-Stripe",
    price: 109.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Nexus",
    description: "Nexus men's Haze Training Top",
    price: 270.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Nexus",
    description: "Nexus men's Modern Camo Training Top",
    price: 350.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Nexus",
    description: "Nexus Men Camo Training T-Shirt",
    price: 350.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Nexus",
    description: "Nexus men's Nexus Core Collection",
    price: 300.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Ravin",
    description: "Ravin mens Ravin 96441 Side Pocket Printed",
    price: 289.99,
    images: [],
  },
  {
    type: "shirts",
    brandName: "CAESAR",
    description: "CAESAR Men Hoodie With Pants Training Suit Anorak",
    price: 120.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Coup",
    description: "Coup",
    price: 135.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Coup",
    description:
      "Coup mens Coup - Panel Blocked Hooded Sweatshirt with Long Sleeves Hooded Sweatshirt",
    price: 60.0,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Reebok",
    description: "Reebok Men's Wor Sup Ss Graphic Tee T-Shirt",
    price: 50.99,
    images: [],
  },
  {
    type: "shirts",
    brandName: "Generic",
    description: "Men's Lycra Indoor/Outdoor Bengalen Pants",
    price: 99.99,
    images: [],
  },
  {
    type: "womendress",
    brandName: "FG",
    description: "Lycra wine red one size dress",
    price: 75.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "Jamila",
    description:
      "Jamila womens Elbow Sleeves Solid Brown Dress With Hem Elbow Sleeves Solid Brown Dress With Hem",
    price: 149.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "FG",
    description: "Red Wine Peplum Casual Dress For Women",
    price: 400.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "Generic",
    description: "Yellow Women Chiffon Dress with Lining",
    price: 450.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "Generic",
    description: "Green Off Shoulder Chiffon Women Dress",
    price: 325.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "El Negm ElSharky",
    description: "Long - Half Tunic - Fitted Top",
    price: 225.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "Pinky",
    description: "Long Blouse for women",
    price: 350.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "Generic",
    description: "Black Women Cotton Long Blouse",
    price: 300.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "M.Sou",
    description: "M.Sou Women Tied Neck Collar Solid Blouse ",
    price: 199.0,
    images: [],
  },
  {
    type: "womendress",
    brandName: "Jamila",
    description:
      "Jamila Plain Wide Cuffed Long Sleeves Round Neck Loose Blouse for Women ",
    price: 159.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Dejavu",
    description: "Dejavu",
    price: 59.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Hammer",
    description: "HWBL197-Hammer-Suede lace up with scotch tape boot",
    price: 199.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Mr. Joe",
    description: "Mr. Joe",
    price: 689.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Levent",
    description: "Levent Platform Leather Boot For Women",
    price: 199.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Dejavu",
    description: "Dejavu Lace With Golden Dots Lace Pointed Stiletto - Cream",
    price: 529.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Dejavu",
    description: "Dejavu Decorative",
    price: 487.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Varna",
    description: "VARNA Fashion Heels Shoes Sandal Size For Women ",
    price: 500.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Reebok",
    description:
      "Reebok REEBOK ROYAL COMPLE FTWWHT/HINMIN/ACIYEL GW5289 TENNIS SHOES - LOW (NON FOOTBALL) For Women ",
    price: 1.039,
    images: [],
  },
  {
    type: "shoes",
    brandName: " Dejavu",
    description: "Dejavu Strass Detailed Lace Fashion Sneakers ",
    price: 439.0,
    images: [],
  },
  {
    type: "shoes",
    brandName: "Grinta",
    description: "Grinta Women Fashion Sneakers ",
    price: 700.0,
    images: [],
  },
];
