[
  {
    type: "shoes",
    brandName: " Grinta",
    description: "Grinta_Men_Fashion Sneakers-Black_44EU",
    price: "209.00",
    image: [
      { src1: "./images/men_shoes/item1.jpg" },
      { src2: "./images/men_shoes/item1previwe2" },
      { src3: "./images/men_shoes/item1previwe3" },
      { src4: "./images/men_shoes/item1previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  activ",
    description: "ACTIV CASUAL FASHION SHOES,WHITE,39",
    price: "599.00",
    image: [
      { src1: "./images/men_shoes/item2.jpg" },
      { src2: "./images/men_shoes/item2previwe" },
      { src3: "./images/men_shoes/item1previwe2" },
      { src4: "./images/men_shoes/item1previwe3" },
      { src4: "./images/men_shoes/item1previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  Reebok",
    description: "Reebok FLOATRIDE ENERGY 3.0 Shoes for Men white EU",
    price: "1,369.00 ",
    image: [
      { src1: "./images/men_shoes/item3.jpg" },
      { src2: "./images/men_shoes/item3previwe1" },
      { src3: "./images/men_shoes/item3previwe2" },
      { src4: "./images/men_shoes/item3previwe3" },
      { src4: "./images/men_shoes/item3previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  adidas",
    description: "adidas Unisex Kids Predator Edge.4 Tf J, Color",
    price: "789.00 ",
    image: [
      { src1: "./images/men_shoes/item4.jpg" },
      { src2: "./images/men_shoes/item4previwe1" },
      { src3: "./images/men_shoes/item4previwe2" },
      { src4: "./images/men_shoes/item4previwe3" },
      { src4: "./images/men_shoes/item4previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  Adidas",
    description: "Adidas VULCRAID3R",
    price: "1,289.00  ",
    image: [
      { src1: "./images/men_shoes/item5.jpg" },
      { src2: "./images/men_shoes/item5previwe1" },
      { src3: "./images/men_shoes/item5previwe2" },
      { src4: "./images/men_shoes/item5previwe3" },
      { src4: "./images/men_shoes/item5previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  adidas",
    description: "Adidas VULCRAID3R K GZ3334 SKATEBOARDING",
    price: "949.00 ",
    image: [
      { src1: "./images/men_shoes/item6.jpg" },
      { src2: "./images/men_shoes/item6previwe1" },
      { src3: "./images/men_shoes/item6previwe2" },
      { src4: "./images/men_shoes/item6previwe3" },
      { src4: "./images/men_shoes/item6previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  adidas",
    description: "Adidas LITE RACER 3.0 GW3023 RUNNING",
    price: "1,089.00 ",
    image: [
      { src1: "./images/men_shoes/item7.jpg" },
      { src2: "./images/men_shoes/item7previwe1" },
      { src3: "./images/men_shoes/item7previwe2" },
      { src4: "./images/men_shoes/item7previwe3" },
      { src4: "./images/men_shoes/item7previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  adidas",
    description: "Adidas X Ghosted.1 Textile Two-Tone Printed Front",
    price: "5,049.00 ",
    image: [
      { src1: "./images/men_shoes/item8.jpg" },
      { src2: "./images/men_shoes/item8previwe1" },
      { src3: "./images/men_shoes/item8previwe2" },
      { src4: "./images/men_shoes/item8previwe3" },
      { src4: "./images/men_shoes/item8previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "Generic",
    description: "Romba Sport Shoes For Men",
    price: "179 ",
    image: [
      { src1: "./images/men_shoes/item9.jpg" },
      { src2: "./images/men_shoes/item9previwe1" },
      { src3: "./images/men_shoes/item9previwe2" },
      { src4: "./images/men_shoes/item9previwe3" },
      { src4: "./images/men_shoes/item9previwe4" },
    ],
  },
  {
    type: "shoes",
    brandName: "  salerno",
    description: "Salerno Mesh Leather-Accent Contrast Side-Stripe",
    price: "109.00 ",
    image: [
      { src1: "./images/men_shoes/item10.jpg" },
      { src2: "./images/men_shoes/item10previwe1" },
      { src3: "./images/men_shoes/item10previwe2" },
      { src4: "./images/men_shoes/item10previwe3" },
      { src4: "./images/men_shoes/item10previwe4" },
    ],
  },
];
